spring:
  application:
    name: scotland

---
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: dev
  webflux:
    base-path: /api
  data:
    mongodb:
      host: localhost
      port: 27017
      username: scotland_dev_admin
      password: Admin123Admin123
      database: scotland_dev
      authentication-database: admin
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/scotland_dev
    username: scotland_dev_admin
    password: Admin123Admin123
    pool:
#      validation-query: SELECT
      enabled: true

auth:
  refresh-token:
    duration: P7D
#    key: s9DLs2WNsrl5hBhkKXtEY8cOkF9hZCzyfwuBSofNY7U=
  header:
    user-id: X-Kisswe-User-Id
  claim:
    issuer: kisswe-auth-service-dev
    audience: gatekeeper-service-dev
    duration: PT15M
  signing-key:
    type: JKS
    filename: signature-keystore-dev.jks
    password: Admin123Admin123
    alias: kisswe-jwt-signature-dev-key
  kakao:
    api-key: 47c0c7761b1531a96b43d1703c934872
    auth:
      base-url: https://kauth.kakao.com
      get-token:
        path: /oauth/token
    user:
      base-url: https://kapi.kakao.com
      get-token-info:
        path: /v1/user/access_token_info
      get-profile:
        path: /v2/user/me


logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters